import type { QuestionNode, Condition } from "./types";

/* ─── Condition helpers ─── */

export function eq(field: string, value: unknown): Condition {
  return { operator: "equals", field, value };
}
export function neq(field: string, value: unknown): Condition {
  return { operator: "notEquals", field, value };
}
export function inc(field: string, value: unknown): Condition {
  return { operator: "includes", field, value };
}
export function incAny(field: string, values: unknown[]): Condition {
  return { operator: "includesAny", field, values };
}
export function incAll(field: string, values: unknown[]): Condition {
  return { operator: "includesAll", field, values };
}
export function exists(field: string): Condition {
  return { operator: "exists", field };
}
export function gt(field: string, value: number): Condition {
  return { operator: "greaterThan", field, value };
}
export function and(...conditions: Condition[]): Condition {
  return { operator: "and", conditions };
}
export function or(...conditions: Condition[]): Condition {
  return { operator: "or", conditions };
}
export function not(condition: Condition): Condition {
  return { operator: "not", condition };
}

/* ─── Question Bank ─── */

export const questionBank: QuestionNode[] = [
  /* ══════════ MACRO STAGE 1: Intent Detection ══════════ */
  {
    id: "services",
    macroStage: 1,
    domain: "intent",
    type: "multiSelect",
    title: "What do you need help with?",
    description: "Choose everything that applies. This shapes your assessment.",
    required: true,
    options: [
      { id: "seo", label: "SEO Growth", value: "seo", tags: ["organic", "search"] },
      { id: "geo", label: "AI Search / GEO", value: "geo", tags: ["organic", "ai", "search"] },
      { id: "website", label: "Website Design or Redesign", value: "website", tags: ["web"] },
      { id: "leads", label: "Lead Generation", value: "leads", tags: ["growth"] },
      { id: "cro", label: "Conversion Optimisation", value: "cro", tags: ["growth", "web"] },
      { id: "ads", label: "Google Ads", value: "ads", tags: ["paid"] },
      { id: "social", label: "Social Media", value: "social", tags: ["paid", "organic"] },
      { id: "automation", label: "AI Automation", value: "automation", tags: ["ops"] },
      { id: "crm", label: "CRM", value: "crm", tags: ["ops"] },
      { id: "branding", label: "Branding", value: "branding", tags: ["brand"] },
      { id: "content", label: "Content Marketing", value: "content", tags: ["organic", "brand"] },
      { id: "unsure", label: "Not Sure — Diagnose My Needs", value: "unsure", tags: ["diagnostic"] },
    ],
    estimatedSeconds: 30,
    analyticsKey: "services",
  },
  {
    id: "businessType",
    macroStage: 1,
    domain: "intent",
    type: "singleSelect",
    title: "What best describes your role?",
    description: "This helps us tailor the assessment.",
    required: true,
    options: [
      { id: "owner", label: "Owner or Founder", value: "owner" },
      { id: "marketing-leader", label: "Marketing Leader", value: "marketing-leader" },
      { id: "marketing-team", label: "Marketing Team Member", value: "marketing-team" },
      { id: "ops-leader", label: "Operations Leader", value: "ops-leader" },
      { id: "sales-leader", label: "Sales Leader", value: "sales-leader" },
      { id: "agency", label: "Agency Partner", value: "agency" },
      { id: "freelancer", label: "Freelancer", value: "freelancer" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 15,
    analyticsKey: "business_type",
  },
  {
    id: "source",
    macroStage: 1,
    domain: "intent",
    type: "singleSelect",
    title: "How did you find ZON?",
    description: "Helps us understand what is working.",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    options: [
      { id: "google", label: "Google Search", value: "google" },
      { id: "chatgpt", label: "ChatGPT or AI Search", value: "chatgpt" },
      { id: "linkedin", label: "LinkedIn", value: "linkedin" },
      { id: "instagram", label: "Instagram", value: "instagram" },
      { id: "referral", label: "Referral", value: "referral" },
      { id: "event", label: "Event", value: "event" },
      { id: "ad", label: "Advertisement", value: "ad" },
      { id: "client", label: "Existing Client", value: "client" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "source",
  },

  /* ══════════ MACRO STAGE 2: Business Intelligence ══════════ */
  {
    id: "companyName",
    macroStage: 2,
    domain: "company",
    type: "text",
    title: "What is your company name?",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    estimatedSeconds: 15,
    analyticsKey: "company_name",
  },
  {
    id: "websiteExists",
    macroStage: 2,
    domain: "company",
    type: "singleSelect",
    title: "Do you have a current website?",
    required: true,
    options: [
      { id: "yes", label: "Yes", value: "yes" },
      { id: "no", label: "Not yet", value: "no" },
      { id: "building", label: "Building one now", value: "building" },
    ],
    invalidatesOnChange: [
      "websiteUrl", "websiteAge", "traffic", "cms", "websitePurpose",
      "websiteSatisfaction", "technicalIssues",
    ],
    estimatedSeconds: 10,
    analyticsKey: "website_exists",
  },
  {
    id: "websiteUrl",
    macroStage: 2,
    domain: "website",
    type: "url",
    title: "What is your website URL?",
    description: "So we can review your online presence.",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    showWhen: eq("websiteExists", "yes"),
    estimatedSeconds: 10,
    analyticsKey: "website_url",
  },
  {
    id: "industry",
    macroStage: 2,
    domain: "company",
    type: "singleSelect",
    title: "What industry are you in?",
    required: true,
    options: [
      { id: "legal", label: "Legal", value: "legal" },
      { id: "healthcare", label: "Healthcare / Dental / Medical", value: "healthcare" },
      { id: "construction", label: "Construction / Trades", value: "construction" },
      { id: "real-estate", label: "Real Estate", value: "real-estate" },
      { id: "home-services", label: "Home Services", value: "home-services" },
      { id: "fitness", label: "Fitness / Wellness", value: "fitness" },
      { id: "finance", label: "Finance / Insurance", value: "finance" },
      { id: "education", label: "Education", value: "education" },
      { id: "ecommerce", label: "Ecommerce / Retail", value: "ecommerce" },
      { id: "restaurant", label: "Restaurant / Hospitality", value: "restaurant" },
      { id: "saas", label: "SaaS / Technology", value: "saas" },
      { id: "manufacturing", label: "Manufacturing", value: "manufacturing" },
      { id: "agency", label: "Agency / Consulting", value: "agency" },
      { id: "nonprofit", label: "Non-profit", value: "nonprofit" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 15,
    analyticsKey: "industry",
  },
  {
    id: "businessModel",
    macroStage: 2,
    domain: "company",
    type: "singleSelect",
    title: "Which best describes your business model?",
    required: true,
    options: [
      { id: "b2c-local", label: "Local service (serves a specific area)", value: "b2c-local" },
      { id: "b2c-national", label: "Consumer brand (national audience)", value: "b2c-national" },
      { id: "b2b-local", label: "B2B (local/regional)", value: "b2b-local" },
      { id: "b2b-national", label: "B2B (national/international)", value: "b2b-national" },
      { id: "ecommerce", label: "Ecommerce (sells products online)", value: "ecommerce" },
      { id: "saas", label: "SaaS / Digital Product", value: "saas" },
      { id: "marketplace", label: "Marketplace / Platform", value: "marketplace" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 15,
    analyticsKey: "business_model",
  },
  {
    id: "teamSize",
    macroStage: 2,
    domain: "company",
    type: "singleSelect",
    title: "How many people are in your team?",
    required: true,
    options: [
      { id: "solo", label: "Just me", value: "solo" },
      { id: "2-10", label: "2–10", value: "2-10" },
      { id: "11-25", label: "11–25", value: "11-25" },
      { id: "26-50", label: "26–50", value: "26-50" },
      { id: "51-200", label: "51–200", value: "51-200" },
      { id: "200+", label: "200+", value: "200+" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "team_size",
  },
  {
    id: "monthlyRevenue",
    macroStage: 2,
    domain: "company",
    type: "singleSelect",
    title: "Approximate monthly revenue (optional)",
    description: "Used to recommend appropriate engagement sizes.",
    required: false,
    allowSkip: true,
    skipLabel: "Prefer not to say",
    options: [
      { id: "under-10k", label: "Under $10k", value: "under-10k" },
      { id: "10k-50k", label: "$10k–$50k", value: "10k-50k" },
      { id: "50k-100k", label: "$50k–$100k", value: "50k-100k" },
      { id: "100k-500k", label: "$100k–$500k", value: "100k-500k" },
      { id: "500k-plus", label: "$500k+", value: "500k+" },
      { id: "undisclosed", label: "Prefer not to say", value: "undisclosed" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "monthly_revenue",
  },

  /* ══════════ MACRO STAGE 3: Current Digital Presence ══════════ */

  /* ── Website module ── */
  {
    id: "websiteAge",
    macroStage: 3,
    domain: "website",
    type: "singleSelect",
    title: "How old is your website?",
    required: true,
    showWhen: eq("websiteExists", "yes"),
    options: [
      { id: "<1", label: "Less than 1 year", value: "<1" },
      { id: "1-3", label: "1–3 years", value: "1-3" },
      { id: "3-5", label: "3–5 years", value: "3-5" },
      { id: "5+", label: "5+ years", value: "5+" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "website_age",
  },
  {
    id: "cms",
    macroStage: 3,
    domain: "website",
    type: "singleSelect",
    title: "What CMS or platform does your website use?",
    required: false,
    allowSkip: true,
    skipLabel: "Not sure",
    showWhen: and(eq("websiteExists", "yes"), or(incAny("services", ["seo", "website", "cro", "leads"]))),
    options: [
      { id: "wordpress", label: "WordPress", value: "wordpress" },
      { id: "shopify", label: "Shopify", value: "shopify" },
      { id: "webflow", label: "Webflow", value: "webflow" },
      { id: "wix", label: "Wix / Squarespace", value: "wix" },
      { id: "custom", label: "Custom-built", value: "custom" },
      { id: "headless", label: "Headless / Jamstack", value: "headless" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "cms",
  },
  {
    id: "websitePurpose",
    macroStage: 3,
    domain: "website",
    type: "multiSelect",
    title: "What is the primary purpose of your website?",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    showWhen: and(eq("websiteExists", "yes"), or(incAny("services", ["seo", "website", "cro", "leads"]))),
    options: [
      { id: "info", label: "Provide information", value: "info" },
      { id: "leads", label: "Generate leads", value: "leads" },
      { id: "sales", label: "Sell products/services", value: "sales" },
      { id: "booking", label: "Accept bookings", value: "booking" },
      { id: "support", label: "Support existing customers", value: "support" },
      { id: "brand", label: "Build brand authority", value: "brand" },
      { id: "other", label: "Other", value: "other" },
    ],
    estimatedSeconds: 15,
    analyticsKey: "website_purpose",
  },
  {
    id: "websiteSatisfaction",
    macroStage: 3,
    domain: "website",
    type: "singleSelect",
    title: "How satisfied are you with your current website?",
    required: true,
    showWhen: eq("websiteExists", "yes"),
    options: [
      { id: "very", label: "Very satisfied", value: "very" },
      { id: "somewhat", label: "Somewhat satisfied", value: "somewhat" },
      { id: "neutral", label: "Neutral", value: "neutral" },
      { id: "dissatisfied", label: "Somewhat dissatisfied", value: "dissatisfied" },
      { id: "very-dissatisfied", label: "Very dissatisfied", value: "very-dissatisfied" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "website_satisfaction",
  },

  /* ── New website module (no website exists) ── */
  {
    id: "newWebsiteGoal",
    macroStage: 3,
    domain: "newWebsite",
    type: "multiSelect",
    title: "What should your new website help customers do?",
    description: "Select everything that applies.",
    required: true,
    showWhen: or(eq("websiteExists", "no"), eq("websiteExists", "building")),
    options: [
      { id: "book", label: "Book appointments or services", value: "book" },
      { id: "buy", label: "Buy products or services", value: "buy" },
      { id: "inquire", label: "Submit enquiries", value: "inquire" },
      { id: "learn", label: "Learn about the business", value: "learn" },
      { id: "support", label: "Get support", value: "support" },
      { id: "portal", label: "Access a client portal", value: "portal" },
      { id: "multilingual", label: "Serve multiple languages", value: "multilingual" },
    ],
    estimatedSeconds: 20,
    analyticsKey: "new_website_goal",
  },
  {
    id: "existingBrandAssets",
    macroStage: 3,
    domain: "newWebsite",
    type: "singleSelect",
    title: "Do you have existing brand assets (logo, colours, content)?",
    required: false,
    options: [
      { id: "yes", label: "Yes — we have existing brand assets", value: "yes" },
      { id: "no", label: "No — starting from scratch", value: "no" },
    ],
    allowSkip: true,
    skipLabel: "Skip",
    showWhen: or(eq("websiteExists", "no"), eq("websiteExists", "building")),
    estimatedSeconds: 10,
    analyticsKey: "existing_brand_assets",
  },
  {
    id: "websiteLaunchTimeline",
    macroStage: 3,
    domain: "newWebsite",
    type: "singleSelect",
    title: "When would you like your new website launched?",
    required: true,
    showWhen: or(eq("websiteExists", "no"), eq("websiteExists", "building")),
    options: [
      { id: "asap", label: "As soon as possible", value: "asap" },
      { id: "1-3-months", label: "Within 1–3 months", value: "1-3-months" },
      { id: "3-6-months", label: "Within 3–6 months", value: "3-6-months" },
      { id: "exploring", label: "Just exploring right now", value: "exploring" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "website_launch_timeline",
  },

  /* ── SEO module ── */
  {
    id: "currentSeo",
    macroStage: 3,
    domain: "seo",
    type: "singleSelect",
    title: "Do you currently invest in SEO?",
    required: true,
    showWhen: or(
      incAny("services", ["seo", "geo", "content", "leads"]),
      inc("goal", "rankings"),
    ),
    options: [
      { id: "none", label: "No, nothing", value: "none" },
      { id: "inhouse", label: "In-house team", value: "inhouse" },
      { id: "agency", label: "Working with an agency", value: "agency" },
      { id: "freelancer", label: "Freelancer", value: "freelancer" },
      { id: "unsure", label: "Not sure", value: "unsure" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "current_seo",
  },
  {
    id: "seoSatisfaction",
    macroStage: 3,
    domain: "seo",
    type: "slider",
    title: "How satisfied are you with your current SEO results?",
    description: "1 = Terrible, 10 = Crushing it",
    required: true,
    showWhen: and(
      or(incAny("services", ["seo", "geo"]), inc("goal", "rankings")),
      neq("currentSeo", "none"),
    ),
    estimatedSeconds: 10,
    analyticsKey: "seo_satisfaction",
  },
  {
    id: "seoScope",
    macroStage: 3,
    domain: "seo",
    type: "multiSelect",
    title: "What type of SEO do you need?",
    description: "Select as many as apply.",
    required: true,
    showWhen: or(incAny("services", ["seo", "geo"]), inc("goal", "rankings")),
    options: [
      { id: "local-seo", label: "Local SEO", value: "local-seo" },
      { id: "national-seo", label: "National SEO", value: "national-seo" },
      { id: "international-seo", label: "International SEO", value: "international-seo" },
      { id: "technical-seo", label: "Technical SEO", value: "technical-seo" },
      { id: "content-seo", label: "Content Strategy", value: "content-seo" },
      { id: "entity-seo", label: "Entity / AI Search", value: "entity-seo" },
      { id: "link-building", label: "Authority / Link Building", value: "link-building" },
      { id: "programmatic", label: "Programmatic SEO", value: "programmatic" },
    ],
    estimatedSeconds: 20,
    analyticsKey: "seo_scope",
  },

  /* ── AI Search / GEO module ── */
  {
    id: "aiSearchChecked",
    macroStage: 3,
    domain: "geo",
    type: "singleSelect",
    title: "Have you checked whether AI platforms recommend your business?",
    description: "ChatGPT, Perplexity, Gemini, etc.",
    required: true,
    showWhen: or(
      incAny("services", ["geo", "seo", "content"]),
      inc("goal", "ai-visibility"),
      eq("source", "chatgpt"),
    ),
    options: [
      { id: "yes-appear", label: "Yes, we appear", value: "yes-appear" },
      { id: "yes-not", label: "Yes, we don't appear", value: "yes-not" },
      { id: "no", label: "No, never checked", value: "no" },
      { id: "unaware", label: "Didn't know this existed", value: "unaware" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "ai_search_checked",
  },
  {
    id: "aiPlatforms",
    macroStage: 3,
    domain: "geo",
    type: "multiSelect",
    title: "Which AI platforms matter most to your business?",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    showWhen: or(
      incAny("services", ["geo", "seo", "content"]),
      inc("goal", "ai-visibility"),
    ),
    options: [
      { id: "chatgpt", label: "ChatGPT", value: "chatgpt" },
      { id: "perplexity", label: "Perplexity", value: "perplexity" },
      { id: "gemini", label: "Google Gemini", value: "gemini" },
      { id: "copilot", label: "Microsoft Copilot", value: "copilot" },
      { id: "grok", label: "Grok", value: "grok" },
      { id: "claude", label: "Claude", value: "claude" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "ai_platforms",
  },

  /* ── Local Search module ── */
  {
    id: "localRelevance",
    macroStage: 3,
    domain: "local",
    type: "singleSelect",
    title: "Do you serve customers in specific physical locations?",
    description: "E.g. a city, region, or service area.",
    required: true,
    showWhen: or(
      incAny("services", ["seo", "leads"]),
      eq("businessModel", "b2c-local"),
      eq("businessModel", "b2b-local"),
      incAny("seoScope", ["local-seo"]),
    ),
    options: [
      { id: "yes", label: "Yes — customers come to a physical location", value: "yes" },
      { id: "no", label: "No — location doesn't matter", value: "no" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "local_relevance",
  },
  {
    id: "gbpStatus",
    macroStage: 3,
    domain: "local",
    type: "singleSelect",
    title: "Is your Google Business Profile active?",
    required: true,
    showWhen: eq("localRelevance", "yes"),
    options: [
      { id: "verified", label: "Yes, verified", value: "verified" },
      { id: "unverified", label: "Yes, but not verified", value: "unverified" },
      { id: "not-created", label: "Not yet created", value: "not-created" },
      { id: "na", label: "Not applicable", value: "na" },
    ],
    invalidatesOnChange: ["reviewCount"],
    estimatedSeconds: 10,
    analyticsKey: "gbp_status",
  },
  {
    id: "reviewCount",
    macroStage: 3,
    domain: "local",
    type: "singleSelect",
    title: "How many Google reviews do you have?",
    required: true,
    showWhen: and(eq("localRelevance", true), incAny("gbpStatus", ["verified", "unverified"])),
    options: [
      { id: "0", label: "None yet", value: "0" },
      { id: "1-10", label: "1–10", value: "1-10" },
      { id: "10-50", label: "10–50", value: "10-50" },
      { id: "50+", label: "50+", value: "50+" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "review_count",
  },

  /* ── Traffic question (only when website exists) ── */
  {
    id: "traffic",
    macroStage: 3,
    domain: "website",
    type: "singleSelect",
    title: "Approximate monthly website visitors?",
    description: "An estimate is fine. 'No idea' is perfectly OK.",
    required: false,
    allowSkip: true,
    skipLabel: "Not tracked",
    showWhen: eq("websiteExists", "yes"),
    options: [
      { id: "unknown", label: "No idea", value: "unknown" },
      { id: "0-500", label: "0–500", value: "0-500" },
      { id: "500-5k", label: "500–5k", value: "500-5k" },
      { id: "5k-20k", label: "5k–20k", value: "5k-20k" },
      { id: "20k+", label: "20k+", value: "20k+" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "traffic",
  },

  /* ── Lead gen / CRO module ── */
  {
    id: "monthlyLeads",
    macroStage: 3,
    domain: "leadGeneration",
    type: "singleSelect",
    title: "Approximate monthly leads or enquiries?",
    required: false,
    allowSkip: true,
    skipLabel: "Not tracked",
    showWhen: or(
      incAny("services", ["leads", "cro"]),
      inc("goal", "leads"),
      inc("goal", "sales"),
      inc("pain", "no-leads"),
    ),
    options: [
      { id: "0-5", label: "0–5", value: "0-5" },
      { id: "5-20", label: "5–20", value: "5-20" },
      { id: "20-50", label: "20–50", value: "20-50" },
      { id: "50+", label: "50+", value: "50+" },
      { id: "unknown", label: "Not tracked", value: "unknown" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "monthly_leads",
  },

  /* ── Automation module ── */
  {
    id: "manualHours",
    macroStage: 3,
    domain: "automation",
    type: "singleSelect",
    title: "How many hours per week are spent on manual repetitive tasks?",
    required: false,
    allowSkip: true,
    skipLabel: "Not sure",
    showWhen: or(
      incAny("services", ["automation", "crm"]),
      inc("pain", "manual"),
      inc("pain", "scale"),
    ),
    options: [
      { id: "0-5", label: "0–5 hours", value: "0-5" },
      { id: "5-15", label: "5–15 hours", value: "5-15" },
      { id: "15-30", label: "15–30 hours", value: "15-30" },
      { id: "30+", label: "30+ hours", value: "30+" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "manual_hours",
  },
  {
    id: "currentCrm",
    macroStage: 3,
    domain: "crm",
    type: "singleSelect",
    title: "What CRM do you currently use?",
    required: false,
    allowSkip: true,
    skipLabel: "No CRM",
    showWhen: or(
      incAny("services", ["crm", "automation"]),
      inc("pain", "manual"),
    ),
    options: [
      { id: "hubspot", label: "HubSpot", value: "hubspot" },
      { id: "salesforce", label: "Salesforce", value: "salesforce" },
      { id: "pipedrive", label: "Pipedrive", value: "pipedrive" },
      { id: "gohighlevel", label: "GoHighLevel", value: "gohighlevel" },
      { id: "zoho", label: "Zoho", value: "zoho" },
      { id: "other", label: "Other", value: "other" },
      { id: "none", label: "No CRM", value: "none" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "current_crm",
  },

  /* ══════════ MACRO STAGE 4: Pain and Goal Discovery ══════════ */
  {
    id: "pain",
    macroStage: 4,
    domain: "intent",
    type: "multiSelect",
    title: "What is creating the biggest business impact right now?",
    description: "Select everything that applies. You can identify your primary concern next.",
    required: true,
    options: [
      { id: "no-leads", label: "Not enough qualified leads", value: "no-leads" },
      { id: "no-visibility", label: "Low search visibility", value: "no-visibility" },
      { id: "no-ai", label: "Low AI search visibility", value: "no-ai" },
      { id: "low-conversions", label: "Weak website conversions", value: "low-conversions" },
      { id: "slow-website", label: "Slow or outdated website", value: "slow-website" },
      { id: "high-ad-costs", label: "High acquisition costs", value: "high-ad-costs" },
      { id: "poor-lead-quality", label: "Poor lead quality", value: "poor-lead-quality" },
      { id: "weak-brand", label: "Weak brand authority", value: "weak-brand" },
      { id: "manual", label: "Manual operations / too much admin", value: "manual" },
      { id: "disconnected", label: "Disconnected systems", value: "disconnected" },
      { id: "inconsistent-content", label: "Inconsistent content", value: "inconsistent-content" },
      { id: "cant-scale", label: "Difficulty scaling", value: "cant-scale" },
      { id: "unsure", label: "Not sure", value: "unsure" },
    ],
    estimatedSeconds: 25,
    analyticsKey: "pain",
  },
  {
    id: "goal",
    macroStage: 4,
    domain: "intent",
    type: "singleSelect",
    title: "What is your primary business goal right now?",
    required: true,
    options: [
      { id: "leads", label: "Increase qualified leads", value: "leads" },
      { id: "sales", label: "Increase sales", value: "sales" },
      { id: "reduce-cost", label: "Reduce acquisition cost", value: "reduce-cost" },
      { id: "conversions", label: "Improve conversion rate", value: "conversions" },
      { id: "rankings", label: "Build organic search visibility", value: "rankings" },
      { id: "ai-visibility", label: "Build AI search visibility", value: "ai-visibility" },
      { id: "expansion", label: "Enter new markets", value: "expansion" },
      { id: "authority", label: "Strengthen brand authority", value: "authority" },
      { id: "automation", label: "Automate operations", value: "automation" },
      { id: "reporting", label: "Improve data and reporting", value: "reporting" },
      { id: "launch", label: "Launch a new digital product", value: "launch" },
      { id: "new-website", label: "Build a new website", value: "new-website" },
    ],
    estimatedSeconds: 20,
    analyticsKey: "goal",
  },
  {
    id: "urgency",
    macroStage: 4,
    domain: "intent",
    type: "singleSelect",
    title: "When do you want to start seeing results?",
    required: true,
    options: [
      { id: "immediate", label: "Immediately", value: "immediate" },
      { id: "2-weeks", label: "Within 2 weeks", value: "2-weeks" },
      { id: "1-month", label: "Within 1 month", value: "1-month" },
      { id: "3-months", label: "Within 3 months", value: "3-months" },
      { id: "exploring", label: "Exploring options", value: "exploring" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "urgency",
  },
  {
    id: "blocker",
    macroStage: 4,
    domain: "intent",
    type: "singleSelect",
    title: "What is the main thing holding you back right now?",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    options: [
      { id: "budget", label: "Budget uncertainty", value: "budget" },
      { id: "approval", label: "Internal approval needed", value: "approval" },
      { id: "knowledge", label: "Lack of expertise", value: "knowledge" },
      { id: "time", label: "Lack of time", value: "time" },
      { id: "agency", label: "Current provider", value: "agency" },
      { id: "tech", label: "Technical limitations", value: "tech" },
      { id: "data", label: "Data limitations", value: "data" },
      { id: "capacity", label: "Team capacity", value: "capacity" },
      { id: "strategy", label: "Unclear strategy", value: "strategy" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "blocker",
  },

  /* ══════════ MACRO STAGE 5: Opportunity Diagnosis ══════════ */
  {
    id: "serviceDetails",
    macroStage: 5,
    domain: "intent",
    type: "multiSelect",
    title: "Which specific areas would you like to explore?",
    description: "Generated from your earlier answers.",
    required: false,
    allowSkip: true,
    skipLabel: "Recommend for me",
    showWhen: neq("services", "unsure"),
    options: [
      { id: "technical-seo", label: "Technical SEO", value: "technical-seo" },
      { id: "local-seo", label: "Local SEO", value: "local-seo" },
      { id: "national-seo", label: "National SEO", value: "national-seo" },
      { id: "international-seo", label: "International SEO", value: "international-seo" },
      { id: "geo", label: "AI Search / GEO", value: "geo" },
      { id: "content", label: "Content Strategy", value: "content" },
      { id: "backlinks", label: "Authority / Link Building", value: "backlinks" },
      { id: "redesign", label: "Website Redesign", value: "redesign" },
      { id: "new-website", label: "New Website Build", value: "new-website" },
      { id: "cro", label: "Conversion Optimisation", value: "cro" },
      { id: "lead-gen", label: "Lead Generation", value: "lead-gen" },
      { id: "ads", label: "Paid Search", value: "ads" },
      { id: "social", label: "Social Media", value: "social" },
      { id: "branding", label: "Branding", value: "branding" },
      { id: "crm", label: "CRM Setup", value: "crm" },
      { id: "automation", label: "AI Automation", value: "automation" },
      { id: "chatbot", label: "AI Chatbot", value: "chatbot" },
      { id: "workflow", label: "Workflow Automation", value: "workflow" },
      { id: "reporting", label: "Reporting Automation", value: "reporting" },
      { id: "custom-dev", label: "Custom Development", value: "custom-dev" },
    ],
    estimatedSeconds: 25,
    analyticsKey: "service_details",
  },

  /* ══════════ MACRO STAGE 6: Qualification ══════════ */
  {
    id: "budget",
    macroStage: 6,
    domain: "qualification",
    type: "singleSelect",
    title: "What is your monthly marketing budget range?",
    description: "Helps us scope the right engagement.",
    required: false,
    allowSkip: true,
    skipLabel: "Prefer not to say",
    options: [
      { id: "under-1k", label: "Under $1,000", value: "under-1k" },
      { id: "1k-3k", label: "$1,000–$3,000", value: "1k-3k" },
      { id: "3k-5k", label: "$3,000–$5,000", value: "3k-5k" },
      { id: "5k-10k", label: "$5,000–$10,000", value: "5k-10k" },
      { id: "10k-25k", label: "$10,000–$25,000", value: "10k-25k" },
      { id: "25k-plus", label: "$25,000+", value: "25k+" },
      { id: "guidance", label: "Need guidance", value: "guidance" },
      { id: "undisclosed", label: "Prefer not to say", value: "undisclosed" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "budget",
  },
  {
    id: "decisionMaker",
    macroStage: 6,
    domain: "qualification",
    type: "singleSelect",
    title: "Are you the decision maker for this?",
    required: true,
    options: [
      { id: "yes", label: "Yes, I decide", value: "yes" },
      { id: "approval", label: "I need approval", value: "approval" },
      { id: "research", label: "Just researching", value: "research" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "decision_maker",
  },
  {
    id: "startTimeline",
    macroStage: 6,
    domain: "qualification",
    type: "singleSelect",
    title: "When would you like to begin?",
    required: true,
    options: [
      { id: "today", label: "Today", value: "today" },
      { id: "week", label: "This week", value: "week" },
      { id: "month", label: "This month", value: "month" },
      { id: "quarter", label: "Within 3 months", value: "quarter" },
      { id: "unsure", label: "Not sure yet", value: "unsure" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "start_timeline",
  },
  {
    id: "preferredContact",
    macroStage: 6,
    domain: "qualification",
    type: "singleSelect",
    title: "How should we reach you?",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    options: [
      { id: "email", label: "Email", value: "email" },
      { id: "whatsapp", label: "WhatsApp", value: "whatsapp" },
      { id: "phone", label: "Phone", value: "phone" },
      { id: "meet", label: "Google Meet", value: "meet" },
      { id: "zoom", label: "Zoom", value: "zoom" },
    ],
    estimatedSeconds: 10,
    analyticsKey: "preferred_contact",
  },

  /* ══════════ MACRO STAGE 7: Contact ══════════ */
  {
    id: "name",
    macroStage: 7,
    domain: "contact",
    type: "text",
    title: "What is your name?",
    required: true,
    estimatedSeconds: 15,
    analyticsKey: "name",
  },
  {
    id: "email",
    macroStage: 7,
    domain: "contact",
    type: "email",
    title: "Your email address",
    description: "Where we will send your personalised Growth Report.",
    required: true,
    validate: (value) => {
      if (typeof value !== "string" || !value.includes("@") || !value.includes(".")) {
        return "Please enter a valid email address.";
      }
      return null;
    },
    estimatedSeconds: 15,
    analyticsKey: "email",
  },
  {
    id: "phone",
    macroStage: 7,
    domain: "contact",
    type: "phone",
    title: "Phone number (optional)",
    description: "For a faster follow-up if you prefer.",
    required: false,
    allowSkip: true,
    skipLabel: "Skip — prefer email",
    estimatedSeconds: 10,
    analyticsKey: "phone",
  },
  {
    id: "country",
    macroStage: 7,
    domain: "contact",
    type: "text",
    title: "Where are you based?",
    description: "We operate globally.",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    estimatedSeconds: 10,
    analyticsKey: "country",
  },
  {
    id: "notes",
    macroStage: 7,
    domain: "contact",
    type: "text",
    title: "Anything else we should know? (optional)",
    required: false,
    allowSkip: true,
    skipLabel: "Skip",
    estimatedSeconds: 15,
    analyticsKey: "notes",
  },
];

/* ─── Macro stage labels ─── */
export const stageLabels: Record<number, string> = {
  1: "Intent Detection",
  2: "Business Intelligence",
  3: "Current Digital Presence",
  4: "Pain and Goal Discovery",
  5: "Opportunity Diagnosis",
  6: "Commercial Qualification",
  7: "Contact & Personalised Report",
};

/* ─── Domain display labels ─── */
export const domainLabels: Record<string, string> = {
  website: "Website Foundation",
  newWebsite: "New Website Opportunity",
  seo: "SEO Maturity",
  geo: "AI Search Readiness",
  local: "Local Search Readiness",
  leadGeneration: "Lead Generation Maturity",
  automation: "Automation Readiness",
  crm: "CRM Maturity",
  branding: "Brand Authority",
  content: "Content Maturity",
};

/* ─── Services list for affinity scoring ─── */
export const serviceList = [
  "technical-seo", "local-seo", "national-seo", "international-seo",
  "ai-search-geo", "content-strategy", "authority-building",
  "website-design", "website-redesign", "conversion-optimisation",
  "lead-generation", "paid-search", "social-media", "branding",
  "crm-setup", "ai-automation", "reporting-automation", "custom-development",
] as const;

export interface ServiceConfig {
  id: string;
  label: string;
  relevantDomains: string[];
  relevantServices: string[];
  relevantPains: string[];
  relevantGoals: string[];
}

export const serviceConfigs: ServiceConfig[] = [
  { id: "technical-seo", label: "Technical SEO", relevantDomains: ["seo"], relevantServices: ["seo"], relevantPains: ["no-visibility"], relevantGoals: ["rankings"] },
  { id: "local-seo", label: "Local SEO", relevantDomains: ["local", "seo"], relevantServices: ["seo"], relevantPains: ["no-visibility"], relevantGoals: ["rankings", "leads"] },
  { id: "ai-search-geo", label: "AI Search / GEO", relevantDomains: ["geo", "seo", "content"], relevantServices: ["geo", "content"], relevantPains: ["no-ai"], relevantGoals: ["ai-visibility", "authority"] },
  { id: "content-strategy", label: "Content Strategy", relevantDomains: ["content", "seo"], relevantServices: ["content", "seo"], relevantPains: ["inconsistent-content", "no-visibility", "no-ai"], relevantGoals: ["rankings", "ai-visibility", "authority"] },
  { id: "authority-building", label: "Authority / Link Building", relevantDomains: ["seo", "content"], relevantServices: ["seo", "content"], relevantPains: ["no-visibility", "weak-brand"], relevantGoals: ["rankings", "authority"] },
  { id: "website-design", label: "New Website Design", relevantDomains: ["newWebsite"], relevantServices: ["website"], relevantPains: ["slow-website"], relevantGoals: ["new-website", "launch"] },
  { id: "website-redesign", label: "Website Redesign", relevantDomains: ["website"], relevantServices: ["website"], relevantPains: ["slow-website", "low-conversions"], relevantGoals: ["conversions", "new-website"] },
  { id: "conversion-optimisation", label: "Conversion Optimisation", relevantDomains: ["website", "cro"], relevantServices: ["cro"], relevantPains: ["low-conversions", "slow-website"], relevantGoals: ["conversions", "sales"] },
  { id: "lead-generation", label: "Lead Generation", relevantDomains: ["leadGeneration"], relevantServices: ["leads"], relevantPains: ["no-leads", "poor-lead-quality"], relevantGoals: ["leads", "sales"] },
  { id: "paid-search", label: "Paid Search", relevantDomains: ["paidMedia"], relevantServices: ["ads"], relevantPains: ["high-ad-costs"], relevantGoals: ["leads", "sales", "reduce-cost"] },
  { id: "social-media", label: "Social Media", relevantDomains: ["social"], relevantServices: ["social"], relevantPains: ["no-leads", "weak-brand"], relevantGoals: ["leads", "authority"] },
  { id: "branding", label: "Branding", relevantDomains: ["branding"], relevantServices: ["branding"], relevantPains: ["weak-brand", "inconsistent-content"], relevantGoals: ["authority"] },
  { id: "crm-setup", label: "CRM Setup", relevantDomains: ["crm"], relevantServices: ["crm"], relevantPains: ["disconnected", "manual"], relevantGoals: ["reporting", "automation"] },
  { id: "ai-automation", label: "AI Automation", relevantDomains: ["automation"], relevantServices: ["automation"], relevantPains: ["manual", "disconnected", "cant-scale"], relevantGoals: ["automation"] },
  { id: "reporting-automation", label: "Reporting Automation", relevantDomains: ["automation"], relevantServices: ["automation"], relevantPains: ["manual", "disconnected"], relevantGoals: ["reporting", "automation"] },
  { id: "custom-development", label: "Custom Development", relevantDomains: ["automation"], relevantServices: [], relevantPains: ["disconnected", "manual", "cant-scale"], relevantGoals: ["launch", "automation"] },
];

export const urgencyValue: Record<string, number> = {
  immediate: 10,
  "2-weeks": 7,
  "1-month": 5,
  "3-months": 3,
  exploring: 1,
};

export const painSeverity: Record<string, number> = {
  "no-leads": 9,
  "no-visibility": 8,
  "no-ai": 7,
  "low-conversions": 7,
  "slow-website": 6,
  "high-ad-costs": 6,
  "poor-lead-quality": 7,
  "weak-brand": 6,
  manual: 5,
  disconnected: 5,
  "inconsistent-content": 4,
  "cant-scale": 7,
};
